# Generated by Django 5.2 on 2025-05-20 16:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("owner", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_private", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="GitHubProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_username", models.CharField(max_length=255)),
                (
                    "github_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("avatar_url", models.URLField(blank=True, null=True)),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_synced",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommitHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commit_hash", models.CharField(max_length=40)),
                ("commit_message", models.TextField()),
                ("commit_date", models.DateTimeField()),
                ("lines_added", models.IntegerField(default=0)),
                ("lines_deleted", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="codetrack.githubprofile",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="codetrack.repository",
                    ),
                ),
            ],
            options={
                "unique_together": {("repository", "commit_hash")},
            },
        ),
        migrations.CreateModel(
            name="UserRepositoryStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commits", models.IntegerField(default=0)),
                ("lines_added", models.IntegerField(default=0)),
                ("lines_deleted", models.IntegerField(default=0)),
                ("net_lines", models.IntegerField(default=0)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repo_stats",
                        to="codetrack.githubprofile",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_stats",
                        to="codetrack.repository",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User repository statistics",
                "unique_together": {("profile", "repository")},
            },
        ),
    ]
