# Generated by Django 5.2 on 2025-05-17 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL to be monitored (optional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("interval_days", models.PositiveIntegerField(default=0)),
                ("interval_hours", models.PositiveIntegerField(default=0)),
                ("interval_minutes", models.PositiveIntegerField(default=5)),
                ("grace_days", models.PositiveIntegerField(default=0)),
                ("grace_hours", models.PositiveIntegerField(default=0)),
                ("grace_minutes", models.PositiveIntegerField(default=5)),
                (
                    "ping_url",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "notify_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("notify_webhook", models.URLField(blank=True, null=True)),
                ("last_ping", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_up", models.BooleanField(default=False)),
                (
                    "response_time_threshold",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Maximum acceptable response time in milliseconds",
                    ),
                ),
                (
                    "avg_response_time",
                    models.FloatField(
                        default=0, help_text="Average response time in milliseconds"
                    ),
                ),
                (
                    "max_response_time",
                    models.FloatField(
                        default=0, help_text="Maximum response time in milliseconds"
                    ),
                ),
                (
                    "min_response_time",
                    models.FloatField(
                        default=0, help_text="Minimum response time in milliseconds"
                    ),
                ),
                (
                    "total_pings",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of successful pings"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FailedHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("failed_at", models.DateTimeField(auto_now_add=True)),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_time", models.DateTimeField(blank=True, null=True)),
                (
                    "health_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="health_check.healthcheck",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthCheckLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                ("additional_data", models.JSONField(blank=True, null=True)),
                (
                    "health_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="health_check.healthcheck",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
